markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html
excerpt_separator: "<!-- more -->"

github: qif618
author: "QIF"
email: 729785034@qq.com
name: "QIF"
url: http://www.98life.com
domain: www.98life.com
all_categories: [
["python", "Python","/python/index.html"], 
["hibernate", "Hibernate","/hibernate/index.html"],
["spring", "Spring","/spring/index.html"], 
["mybatis", "Mybatis","/posts/index.html"],
["git", "Git","/git/index.html"], 
["linux", "Linux","/linux/index.html"], 
["web", "Web","/web/index.html"],
["about", "关于","/about.html"]
]

paginate: 6
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
