markdown: kramdown
highlighter: rouge
permalink: /qif/:categories/:title.html
excerpt_separator: "<!-- more -->"

github: qif618
author: "QIF"
email: 729785034@qq.com
name: "QIF"
url: http://www.98life.com
domain: www.98life.com
all_categories: [
["python", "Python","/qif/python/index.html"], 
["hibernate", "Hibernate","/qif/hibernate/index.html"],
["spring", "Spring","/qif/spring/index.html"], 
["mybatis", "Mybatis","/qif/mybatis/index.html"],
["git", "Git","/qif/git/index.html"], 
["linux", "Linux","/qif/linux/index.html"], 
["web", "Web","/qif/web/index.html"],
["other", "Other","/qif/other/index.html"],
["about", "关于","/qif/aboutMe.html"]
]

paginate: 6
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

plugins:
 - jekyll-paginate
